import { useEffect, useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { medicationLogApi } from '@/db/api';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { Download, FileText, Printer } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import jsPDF from 'jspdf';
import type { MedicationLog } from '@/types';

export default function AnalyticsPage() {
  const { user, profile } = useAuth();
  const { toast } = useToast();
  const [logs, setLogs] = useState<MedicationLog[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!user) return;

    const loadLogs = async () => {
      try {
        const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
        const data = await medicationLogApi.getLogs(user.id, thirtyDaysAgo);
        setLogs(data);
      } catch (error) {
        console.error('Error loading logs:', error);
      } finally {
        setLoading(false);
      }
    };

    loadLogs();
  }, [user]);

  const adherenceData = [
    { name: 'Taken', value: logs.filter(l => l.status === 'taken').length, color: 'hsl(var(--success))' },
    { name: 'Missed', value: logs.filter(l => l.status === 'missed').length, color: 'hsl(var(--destructive))' },
    { name: 'Skipped', value: logs.filter(l => l.status === 'skipped').length, color: 'hsl(var(--warning))' },
    { name: 'Pending', value: logs.filter(l => l.status === 'pending').length, color: 'hsl(var(--muted))' },
  ];

  const weeklyData = Array.from({ length: 7 }, (_, i) => {
    const date = new Date(Date.now() - (6 - i) * 24 * 60 * 60 * 1000);
    const dayLogs = logs.filter(log => {
      const logDate = new Date(log.scheduled_time);
      return logDate.toDateString() === date.toDateString();
    });

    return {
      day: date.toLocaleDateString('en-US', { weekday: 'short' }),
      taken: dayLogs.filter(l => l.status === 'taken').length,
      missed: dayLogs.filter(l => l.status === 'missed').length,
    };
  });

  const adherenceRate = logs.length > 0
    ? Math.round((logs.filter(l => l.status === 'taken').length / logs.length) * 100)
    : 0;

  const exportToPDF = () => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.text('MediCare Companion', 105, 15, { align: 'center' });
    doc.setFontSize(16);
    doc.text('Medication Adherence Report', 105, 25, { align: 'center' });

    // Patient Information
    doc.setFontSize(12);
    doc.text('Patient Information', 20, 40);
    doc.setFontSize(10);
    doc.text(`Name: ${profile?.full_name || profile?.username || 'N/A'}`, 20, 50);
    doc.text(`Email: ${user?.email || profile?.email || 'N/A'}`, 20, 57);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 20, 64);

    // Statistics
    doc.setFontSize(12);
    doc.text('Adherence Statistics (Last 30 Days)', 20, 80);
    doc.setFontSize(10);
    doc.text(`Overall Adherence Rate: ${adherenceRate}%`, 20, 90);
    doc.text(`Total Doses: ${logs.length}`, 20, 97);
    doc.text(`Doses Taken: ${logs.filter(l => l.status === 'taken').length}`, 20, 104);
    doc.text(`Doses Missed: ${logs.filter(l => l.status === 'missed').length}`, 20, 111);
    doc.text(`Doses Skipped: ${logs.filter(l => l.status === 'skipped').length}`, 20, 118);

    // Medical History
    if (profile?.medical_history) {
      doc.setFontSize(12);
      doc.text('Medical History', 20, 135);
      doc.setFontSize(10);
      doc.text(`Condition: ${profile.medical_history}`, 20, 145);
    }

    if (profile?.allergies) {
      doc.text(`Allergies: ${profile.allergies}`, 20, 152);
    }

    // Footer
    doc.setFontSize(8);
    doc.text('This report is generated by MediCare Companion for personal health management.', 105, 280, { align: 'center' });
    doc.text('Please consult your healthcare provider for medical advice.', 105, 285, { align: 'center' });

    doc.save(`medication-report-${new Date().toISOString().split('T')[0]}.pdf`);

    toast({
      title: 'Report Exported',
      description: 'Your medication report has been downloaded as PDF.',
    });
  };

  const exportToCSV = () => {
    const headers = ['Date', 'Time', 'Status', 'Notes'];
    const rows = logs.map(log => [
      new Date(log.scheduled_time).toLocaleDateString(),
      new Date(log.scheduled_time).toLocaleTimeString(),
      log.status,
      log.notes || ''
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `medication-logs-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    window.URL.revokeObjectURL(url);

    toast({
      title: 'Data Exported',
      description: 'Your medication logs have been downloaded as CSV.',
    });
  };

  const handlePrint = () => {
    window.print();
    toast({
      title: 'Print Dialog',
      description: 'Opening print dialog...',
    });
  };

  if (loading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-12 w-64 bg-muted" />
        <Skeleton className="h-96 bg-muted" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
        <div>
          <h1 className="text-3xl font-bold">Analytics</h1>
          <p className="text-muted-foreground">Track your medication adherence and progress</p>
        </div>
        <div className="flex gap-2">
          <Button onClick={exportToPDF} variant="outline">
            <FileText className="mr-2 h-4 w-4" />
            Export PDF
          </Button>
          <Button onClick={exportToCSV} variant="outline">
            <Download className="mr-2 h-4 w-4" />
            Export CSV
          </Button>
          <Button onClick={handlePrint} variant="outline">
            <Printer className="mr-2 h-4 w-4" />
            Print
          </Button>
        </div>
      </div>

      <div className="grid gap-6 xl:grid-cols-3">
        <Card>
          <CardHeader>
            <CardTitle>Adherence Rate</CardTitle>
            <CardDescription>Last 30 days</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-4xl font-bold text-primary">{adherenceRate}%</div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Total Doses</CardTitle>
            <CardDescription>Last 30 days</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-4xl font-bold">{logs.length}</div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Doses Taken</CardTitle>
            <CardDescription>Last 30 days</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-4xl font-bold text-success">
              {logs.filter(l => l.status === 'taken').length}
            </div>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="overview" className="w-full">
        <TabsList>
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="weekly">Weekly Trend</TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Adherence Distribution</CardTitle>
              <CardDescription>Breakdown of your medication status</CardDescription>
            </CardHeader>
            <CardContent>
              <ResponsiveContainer width="100%" height={300}>
                <PieChart>
                  <Pie
                    data={adherenceData}
                    cx="50%"
                    cy="50%"
                    labelLine={false}
                    label={({ name, value }) => `${name}: ${value}`}
                    outerRadius={100}
                    fill="#8884d8"
                    dataKey="value"
                  >
                    {adherenceData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="weekly" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Weekly Adherence Trend</CardTitle>
              <CardDescription>Last 7 days performance</CardDescription>
            </CardHeader>
            <CardContent>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={weeklyData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="day" />
                  <YAxis />
                  <Tooltip />
                  <Legend />
                  <Bar dataKey="taken" fill="hsl(var(--success))" name="Taken" />
                  <Bar dataKey="missed" fill="hsl(var(--destructive))" name="Missed" />
                </BarChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
